config/routes.rb
FoodWebBuilder::Application.routes.draw do
  
  match 'feedbacks' => 'feedbacks#create', :as => :feedback

  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback

  resources :forums


	#For Auto Complete
  	resources :nodes do
  	get :autocomplete_node_working_name, :on => :collection
	end
	#For Auto Complete
  	resources :citations do
  	get :autocomplete_citation_title, :on => :collection
	end


	#For Google Maps
	match 'remove_polygon' => 'location_data#remove_polygon'
	
	#For Node Search
	match 'search' => 'dashboard#search', :as => "search"
	match 'search_by_tsn' => 'nodes#search_by_tsn'
	match 'stage_form' => 'stages#stage_form'
	match 'stage_save' => 'stages#stage_save'
	# for interactions
	match 'search_stage' => 'stages#search_stage'
	match 'create_stage' => 'stages#create_stage'
	match 'interactions' => 'dashboard#add_interactions'
	match 'search_interactions' => 'dashboard#search_interactions'
	match 'add_competition' => 'competition_interaction_observations#add_competition'
	match 'add_facilitation' => 'facilitation_interaction_observations#add_facilitation'
	match 'add_parasitic' => 'parasitic_interaction_observations#add_parasitic'
	match 'add_trophic' => 'trophic_interaction_observations#add_trophic'
	#For Citations
	match 'authors/full_name' => 'authors#full_name'
  match 'auhtors/create_author' => 'authors#create_author'
	resources :projects
 

		#Load resources for models
	
	resources :authors
	resources :author_cites
	resources :citations
	resources :competition_interactions
	resources :competition_interaction_observations
	resources :facilitation_interactions
	resources :facilitation_interaction_observations
	resources :functional_groups
	resources :locations
	resources :location_data
	resources :nodes
	resources :node_max_ages
	resources :node_ranges
	resources :non_itis
	resources :parasitic_interactions
	resources :parasitic_interaction_observations
	resources :stages
	resources :stage_biomass_changes
	resources :stage_biomass_densities
	resources :stage_consume_biomass_ratios
	resources :stage_consumer_strategies
	resources :stage_drymasses
	resources :stage_durations
	resources :stage_fecundities
	resources :stage_habitats
	resources :stage_habitat_descriptors
	resources :stage_lengths
	resources :stage_length_fecundities
	resources :stage_length_weights
	resources :stage_lifestyles
	resources :stage_masses
	resources :stage_max_depths
	resources :stage_mobilities
	resources :stage_populations
	resources :stage_prod_biomass_ratios
	resources :stage_prod_consum_ratios
	resources :stage_reproductive_strategies
	resources :stage_residencies
	resources :stage_residency_times
	resources :stage_unassimilated_consum_ratios
	resources :trophic_interactions
	
	
	# Mount rails admin
	mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
	
	# Configure routes for authenticated User to dashboard
  authenticated :user do
  	root :to => 'dashboard#index'
  	devise_for :users
  	resources :users
  end
  
  # Default root to home/index.html.erb
  root :to =>"home#index"
  # Overriding the devise registrations controller
	devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  
  # add some matching to make coding easier
  match 'about' => 'home#about'
  match 'help' => 'home#help'
  match 'export' => 'home#export'
  match 'visualization' => 'visualization#index'
  match 'dataentry' => 'dashboard#dataentry'
	match 'edit_user_path' => 'users_registrations#edit'
	match 'home' => 'home#index'

	
end

app/models/parasitic_interaction_observation.rb
class ParasiticInteractionObservation < ActiveRecord::Base

  OBSERVATIONS = ["field observation", "laboratory observation","chemical","gut","inferred",
  "expert opinion","fishery","nest contents","scat","forensic"]
  PARASITICS = ["pathogen","castrator","parasitoid","trophically transmitted larva"]
  ENDOECTO = ["endo","ecto"]
  LETHAL = ["benign","lethal"] 
  enum :observation_type, [:'field_observation',:'laboratory observation',:'chemical',:'gut',:'inferred',:'expert opinion',:'fishery',:'nest contents',:'scat',:'forensic']
  enum :parasite_type, [:'pathogen',:'castrator',:'parasitoid',:'trophically transmitted larva']
  enum :endo_ecto, [:'endo',:'ecto']
  enum :lethality, [:'benign',:'lethal']
  attr_accessible :citation_id, :comment, :datum, :endo_ecto, :intensity, :lethality, :location_id, :observation_type, :parasite_type, :parasitic_interaction_id, :prevalence, :user_id, :project_id, :mod, :approved
  belongs_to :citation
  belongs_to :project
  belongs_to :parasitic_interaction
  belongs_to :user
  has_one :location
end

app/controllers/parasitic_interaction_observations_controller.rb
class ParasiticInteractionObservationsController < ApplicationController
	
	#Add parasitic observation
    def add_parasitic
	@stage1 = params[:parasitic_interaction_observation][:stage1]
	@stage2 = params[:parasitic_interaction_observation][:stage2]
	params[:parasitic_interaction_observation].delete(:stage1)
	params[:parasitic_interaction_observation].delete(:stage2)
    @parasitic_interaction_observation = ParasiticInteractionObservation.new(params[:parasitic_interaction_observation])
	@parasitic_interaction_observation.user_id = current_user.id
	@parasitic_interaction_observation.project_id = current_user.project_id
	@parasitic_interaction_observation.location_id = 0
	@parasitic_interaction_observation.parasitic_interaction_id = ParasiticInteraction.where(:stage_1_id => @stage1,
	:stage_2_id => @stage2).first.id
	render :json => [@parasitic_interaction_observation.save]
	end





  # GET /parasitic_interaction_observations
  # GET /parasitic_interaction_observations.json
  def index
    @parasitic_interaction_observations = ParasiticInteractionObservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parasitic_interaction_observations }
    end
  end

  # GET /parasitic_interaction_observations/1
  # GET /parasitic_interaction_observations/1.json
  def show
    @parasitic_interaction_observation = ParasiticInteractionObservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @parasitic_interaction_observation }
    end
  end

  # GET /parasitic_interaction_observations/new
  # GET /parasitic_interaction_observations/new.json
  def new
    @parasitic_interaction_observation = ParasiticInteractionObservation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @parasitic_interaction_observation }
    end
  end

  # GET /parasitic_interaction_observations/1/edit
  def edit
    @parasitic_interaction_observation = ParasiticInteractionObservation.find(params[:id])
  end

  # POST /parasitic_interaction_observations
  # POST /parasitic_interaction_observations.json
  def create
    @parasitic_interaction_observation = ParasiticInteractionObservation.new(params[:parasitic_interaction_observation])

    respond_to do |format|
      if @parasitic_interaction_observation.save
        format.html { redirect_to @parasitic_interaction_observation, notice: 'Parasitic interaction observation was successfully created.' }
        format.json { render json: @parasitic_interaction_observation, status: :created, location: @parasitic_interaction_observation }
      else
        format.html { render action: "new" }
        format.json { render json: @parasitic_interaction_observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parasitic_interaction_observations/1
  # PUT /parasitic_interaction_observations/1.json
  def update
    @parasitic_interaction_observation = ParasiticInteractionObservation.find(params[:id])

    respond_to do |format|
      if @parasitic_interaction_observation.update_attributes(params[:parasitic_interaction_observation])
        format.html { redirect_to @parasitic_interaction_observation, notice: 'Parasitic interaction observation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @parasitic_interaction_observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parasitic_interaction_observations/1
  # DELETE /parasitic_interaction_observations/1.json
  def destroy
    @parasitic_interaction_observation = ParasiticInteractionObservation.find(params[:id])
    @parasitic_interaction_observation.destroy

    respond_to do |format|
      format.html { redirect_to parasitic_interaction_observations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/parasitic_interaction_observations_helper.rb
module ParasiticInteractionObservationsHelper
end

app/views/parasitic_interaction_observations/_form.html.erb
<%= form_for(@parasitic_interaction_observation) do |f| %>
  <% if @parasitic_interaction_observation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parasitic_interaction_observation.errors.count, "error") %> prohibited this parasitic_interaction_observation from being saved:</h2>

      <ul>
      <% @parasitic_interaction_observation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cite_id %><br />
    <%= f.number_field :cite_id %>
  </div>
  <div class="field">
    <%= f.label :parasitic_interaction_id %><br />
    <%= f.number_field :parasitic_interaction_id %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br />
    <%= f.number_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :endo_ecto %><br />
    <%= f.text_field :endo_ecto %>
  </div>
  <div class="field">
    <%= f.label :lethality %><br />
    <%= f.text_field :lethality %>
  </div>
  <div class="field">
    <%= f.label :prevalence %><br />
    <%= f.text_field :prevalence %>
  </div>
  <div class="field">
    <%= f.label :intensity %><br />
    <%= f.text_field :intensity %>
  </div>
  <div class="field">
    <%= f.label :parasite_type %><br />
    <%= f.text_field :parasite_type %>
  </div>
  <div class="field">
    <%= f.label :observation_type %><br />
    <%= f.text_field :observation_type %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :datum %><br />
    <%= f.text_field :datum %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parasitic_interaction_observations/edit.html.erb
<h1>Editing parasitic_interaction_observation</h1>

<%= render 'form' %>

<%= link_to 'Show', @parasitic_interaction_observation %> |
<%= link_to 'Back', parasitic_interaction_observations_path %>

app/views/parasitic_interaction_observations/index.html.erb
<h1>Listing parasitic_interaction_observations</h1>

<table>
  <tr>
    <th>Cite</th>
    <th>Parasitic interaction</th>
    <th>Location</th>
    <th>Endo ecto</th>
    <th>Lethality</th>
    <th>Prevalence</th>
    <th>Intensity</th>
    <th>Parasite type</th>
    <th>Observation type</th>
    <th>Comment</th>
    <th>Datum</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parasitic_interaction_observations.each do |parasitic_interaction_observation| %>
  <tr>
    <td><%= parasitic_interaction_observation.cite_id %></td>
    <td><%= parasitic_interaction_observation.parasitic_interaction_id %></td>
    <td><%= parasitic_interaction_observation.location_id %></td>
    <td><%= parasitic_interaction_observation.endo_ecto %></td>
    <td><%= parasitic_interaction_observation.lethality %></td>
    <td><%= parasitic_interaction_observation.prevalence %></td>
    <td><%= parasitic_interaction_observation.intensity %></td>
    <td><%= parasitic_interaction_observation.parasite_type %></td>
    <td><%= parasitic_interaction_observation.observation_type %></td>
    <td><%= parasitic_interaction_observation.comment %></td>
    <td><%= parasitic_interaction_observation.datum %></td>
    <td><%= parasitic_interaction_observation.user_id %></td>
    <td><%= link_to 'Show', parasitic_interaction_observation %></td>
    <td><%= link_to 'Edit', edit_parasitic_interaction_observation_path(parasitic_interaction_observation) %></td>
    <td><%= link_to 'Destroy', parasitic_interaction_observation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Parasitic interaction observation', new_parasitic_interaction_observation_path %>

app/views/parasitic_interaction_observations/new.html.erb
<h1>New parasitic_interaction_observation</h1>

<%= render 'form' %>

<%= link_to 'Back', parasitic_interaction_observations_path %>

app/views/parasitic_interaction_observations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cite:</b>
  <%= @parasitic_interaction_observation.cite_id %>
</p>

<p>
  <b>Parasitic interaction:</b>
  <%= @parasitic_interaction_observation.parasitic_interaction_id %>
</p>

<p>
  <b>Location:</b>
  <%= @parasitic_interaction_observation.location_id %>
</p>

<p>
  <b>Endo ecto:</b>
  <%= @parasitic_interaction_observation.endo_ecto %>
</p>

<p>
  <b>Lethality:</b>
  <%= @parasitic_interaction_observation.lethality %>
</p>

<p>
  <b>Prevalence:</b>
  <%= @parasitic_interaction_observation.prevalence %>
</p>

<p>
  <b>Intensity:</b>
  <%= @parasitic_interaction_observation.intensity %>
</p>

<p>
  <b>Parasite type:</b>
  <%= @parasitic_interaction_observation.parasite_type %>
</p>

<p>
  <b>Observation type:</b>
  <%= @parasitic_interaction_observation.observation_type %>
</p>

<p>
  <b>Comment:</b>
  <%= @parasitic_interaction_observation.comment %>
</p>

<p>
  <b>Datum:</b>
  <%= @parasitic_interaction_observation.datum %>
</p>

<p>
  <b>User:</b>
  <%= @parasitic_interaction_observation.user_id %>
</p>


<%= link_to 'Edit', edit_parasitic_interaction_observation_path(@parasitic_interaction_observation) %> |
<%= link_to 'Back', parasitic_interaction_observations_path %>