config/routes.rb
FoodWebBuilder::Application.routes.draw do
  
  match 'feedbacks' => 'feedbacks#create', :as => :feedback

  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback

  resources :forums


	#For Auto Complete
  	resources :nodes do
  	get :autocomplete_node_working_name, :on => :collection
	end
	#For Auto Complete
  	resources :citations do
  	get :autocomplete_citation_title, :on => :collection
	end


	#For Google Maps
	match 'remove_polygon' => 'location_data#remove_polygon'
	
	#For Node Search
	match 'search' => 'dashboard#search', :as => "search"
	match 'search_by_tsn' => 'nodes#search_by_tsn'
	match 'stage_form' => 'stages#stage_form'
	match 'stage_save' => 'stages#stage_save'
	# for interactions
	match 'search_stage' => 'stages#search_stage'
	match 'create_stage' => 'stages#create_stage'
	match 'interactions' => 'dashboard#add_interactions'
	match 'search_interactions' => 'dashboard#search_interactions'
	match 'add_competition' => 'competition_interaction_observations#add_competition'
	match 'add_facilitation' => 'facilitation_interaction_observations#add_facilitation'
	match 'add_parasitic' => 'parasitic_interaction_observations#add_parasitic'
	match 'add_trophic' => 'trophic_interaction_observations#add_trophic'
	#For Citations
	match 'authors/full_name' => 'authors#full_name'
  match 'auhtors/create_author' => 'authors#create_author'
	resources :projects
 

		#Load resources for models
	
	resources :authors
	resources :author_cites
	resources :citations
	resources :competition_interactions
	resources :competition_interaction_observations
	resources :facilitation_interactions
	resources :facilitation_interaction_observations
	resources :functional_groups
	resources :locations
	resources :location_data
	resources :nodes
	resources :node_max_ages
	resources :node_ranges
	resources :non_itis
	resources :parasitic_interactions
	resources :parasitic_interaction_observations
	resources :stages
	resources :stage_biomass_changes
	resources :stage_biomass_densities
	resources :stage_consume_biomass_ratios
	resources :stage_consumer_strategies
	resources :stage_drymasses
	resources :stage_durations
	resources :stage_fecundities
	resources :stage_habitats
	resources :stage_habitat_descriptors
	resources :stage_lengths
	resources :stage_length_fecundities
	resources :stage_length_weights
	resources :stage_lifestyles
	resources :stage_masses
	resources :stage_max_depths
	resources :stage_mobilities
	resources :stage_populations
	resources :stage_prod_biomass_ratios
	resources :stage_prod_consum_ratios
	resources :stage_reproductive_strategies
	resources :stage_residencies
	resources :stage_residency_times
	resources :stage_unassimilated_consum_ratios
	resources :trophic_interactions
	
	
	# Mount rails admin
	mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
	
	# Configure routes for authenticated User to dashboard
  authenticated :user do
  	root :to => 'dashboard#index'
  	devise_for :users
  	resources :users
  end
  
  # Default root to home/index.html.erb
  root :to =>"home#index"
  # Overriding the devise registrations controller
	devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  
  # add some matching to make coding easier
  match 'about' => 'home#about'
  match 'help' => 'home#help'
  match 'export' => 'home#export'
  match 'visualization' => 'visualization#index'
  match 'dataentry' => 'dashboard#dataentry'
	match 'edit_user_path' => 'users_registrations#edit'
	match 'home' => 'home#index'

	
end

app/models/stage_unassimilated_consum_ratio.rb
class StageUnassimilatedConsumRatio < ActiveRecord::Base
  attr_accessible :citation_id, :comment, :datum, :stage_id, :unassimilated_consum_ratio, :user_id, :project_id, :mod, :approved
  belongs_to :citation
  belongs_to :stage
  belongs_to :user
  belongs_to :project
end

app/controllers/stage_unassimilated_consum_ratios_controller.rb
class StageUnassimilatedConsumRatiosController < ApplicationController
  # GET /stage_unassimilated_consum_ratios
  # GET /stage_unassimilated_consum_ratios.json
  def index
    @stage_unassimilated_consum_ratios = StageUnassimilatedConsumRatio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stage_unassimilated_consum_ratios }
    end
  end

  # GET /stage_unassimilated_consum_ratios/1
  # GET /stage_unassimilated_consum_ratios/1.json
  def show
    @stage_unassimilated_consum_ratio = StageUnassimilatedConsumRatio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stage_unassimilated_consum_ratio }
    end
  end

  # GET /stage_unassimilated_consum_ratios/new
  # GET /stage_unassimilated_consum_ratios/new.json
  def new
    @stage_unassimilated_consum_ratio = StageUnassimilatedConsumRatio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stage_unassimilated_consum_ratio }
    end
  end

  # GET /stage_unassimilated_consum_ratios/1/edit
  def edit
    @stage_unassimilated_consum_ratio = StageUnassimilatedConsumRatio.find(params[:id])
  end

  # POST /stage_unassimilated_consum_ratios
  # POST /stage_unassimilated_consum_ratios.json
  def create
    @stage_unassimilated_consum_ratio = StageUnassimilatedConsumRatio.new(params[:stage_unassimilated_consum_ratio])

    respond_to do |format|
      if @stage_unassimilated_consum_ratio.save
        format.html { redirect_to @stage_unassimilated_consum_ratio, notice: 'Stage unassimilated consum ratio was successfully created.' }
        format.json { render json: @stage_unassimilated_consum_ratio, status: :created, location: @stage_unassimilated_consum_ratio }
      else
        format.html { render action: "new" }
        format.json { render json: @stage_unassimilated_consum_ratio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stage_unassimilated_consum_ratios/1
  # PUT /stage_unassimilated_consum_ratios/1.json
  def update
    @stage_unassimilated_consum_ratio = StageUnassimilatedConsumRatio.find(params[:id])

    respond_to do |format|
      if @stage_unassimilated_consum_ratio.update_attributes(params[:stage_unassimilated_consum_ratio])
        format.html { redirect_to @stage_unassimilated_consum_ratio, notice: 'Stage unassimilated consum ratio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stage_unassimilated_consum_ratio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stage_unassimilated_consum_ratios/1
  # DELETE /stage_unassimilated_consum_ratios/1.json
  def destroy
    @stage_unassimilated_consum_ratio = StageUnassimilatedConsumRatio.find(params[:id])
    @stage_unassimilated_consum_ratio.destroy

    respond_to do |format|
      format.html { redirect_to stage_unassimilated_consum_ratios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stage_unassimilated_consum_ratios_helper.rb
module StageUnassimilatedConsumRatiosHelper
end

app/views/stage_unassimilated_consum_ratios/_form.html.erb
<%= form_for(@stage_unassimilated_consum_ratio) do |f| %>
  <% if @stage_unassimilated_consum_ratio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stage_unassimilated_consum_ratio.errors.count, "error") %> prohibited this stage_unassimilated_consum_ratio from being saved:</h2>

      <ul>
      <% @stage_unassimilated_consum_ratio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stage_unassimilated_consum_ratios/edit.html.erb
<h1>Editing stage_unassimilated_consum_ratio</h1>

<%= render 'form' %>

<%= link_to 'Show', @stage_unassimilated_consum_ratio %> |
<%= link_to 'Back', stage_unassimilated_consum_ratios_path %>

app/views/stage_unassimilated_consum_ratios/index.html.erb
<h1>Listing stage_unassimilated_consum_ratios</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stage_unassimilated_consum_ratios.each do |stage_unassimilated_consum_ratio| %>
  <tr>
    <td><%= link_to 'Show', stage_unassimilated_consum_ratio %></td>
    <td><%= link_to 'Edit', edit_stage_unassimilated_consum_ratio_path(stage_unassimilated_consum_ratio) %></td>
    <td><%= link_to 'Destroy', stage_unassimilated_consum_ratio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stage unassimilated consum ratio', new_stage_unassimilated_consum_ratio_path %>

app/views/stage_unassimilated_consum_ratios/new.html.erb
<h1>New stage_unassimilated_consum_ratio</h1>

<%= render 'form' %>

<%= link_to 'Back', stage_unassimilated_consum_ratios_path %>

app/views/stage_unassimilated_consum_ratios/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_stage_unassimilated_consum_ratio_path(@stage_unassimilated_consum_ratio) %> |
<%= link_to 'Back', stage_unassimilated_consum_ratios_path %>