config/routes.rb
FoodWebBuilder::Application.routes.draw do
  
  match 'feedbacks' => 'feedbacks#create', :as => :feedback

  match 'feedbacks/new' => 'feedbacks#new', :as => :new_feedback

  resources :forums


	#For Auto Complete
  	resources :nodes do
  	get :autocomplete_node_working_name, :on => :collection
	end
	#For Auto Complete
  	resources :citations do
  	get :autocomplete_citation_title, :on => :collection
	end


	#For Google Maps
	match 'remove_polygon' => 'location_data#remove_polygon'
	
	#For Node Search
	match 'search' => 'dashboard#search', :as => "search"
	match 'search_by_tsn' => 'nodes#search_by_tsn'
	match 'stage_form' => 'stages#stage_form'
	match 'stage_save' => 'stages#stage_save'
	# for interactions
	match 'search_stage' => 'stages#search_stage'
	match 'create_stage' => 'stages#create_stage'
	match 'interactions' => 'dashboard#add_interactions'
	match 'search_interactions' => 'dashboard#search_interactions'
	match 'add_competition' => 'competition_interaction_observations#add_competition'
	match 'add_facilitation' => 'facilitation_interaction_observations#add_facilitation'
	match 'add_parasitic' => 'parasitic_interaction_observations#add_parasitic'
	match 'add_trophic' => 'trophic_interaction_observations#add_trophic'
	#For Citations
	match 'authors/full_name' => 'authors#full_name'
  match 'auhtors/create_author' => 'authors#create_author'
	resources :projects
 

		#Load resources for models
	
	resources :authors
	resources :author_cites
	resources :citations
	resources :competition_interactions
	resources :competition_interaction_observations
	resources :facilitation_interactions
	resources :facilitation_interaction_observations
	resources :functional_groups
	resources :locations
	resources :location_data
	resources :nodes
	resources :node_max_ages
	resources :node_ranges
	resources :non_itis
	resources :parasitic_interactions
	resources :parasitic_interaction_observations
	resources :stages
	resources :stage_biomass_changes
	resources :stage_biomass_densities
	resources :stage_consume_biomass_ratios
	resources :stage_consumer_strategies
	resources :stage_drymasses
	resources :stage_durations
	resources :stage_fecundities
	resources :stage_habitats
	resources :stage_habitat_descriptors
	resources :stage_lengths
	resources :stage_length_fecundities
	resources :stage_length_weights
	resources :stage_lifestyles
	resources :stage_masses
	resources :stage_max_depths
	resources :stage_mobilities
	resources :stage_populations
	resources :stage_prod_biomass_ratios
	resources :stage_prod_consum_ratios
	resources :stage_reproductive_strategies
	resources :stage_residencies
	resources :stage_residency_times
	resources :stage_unassimilated_consum_ratios
	resources :trophic_interactions
	
	
	# Mount rails admin
	mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
	
	# Configure routes for authenticated User to dashboard
  authenticated :user do
  	root :to => 'dashboard#index'
  	devise_for :users
  	resources :users
  end
  
  # Default root to home/index.html.erb
  root :to =>"home#index"
  # Overriding the devise registrations controller
	devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  
  # add some matching to make coding easier
  match 'about' => 'home#about'
  match 'help' => 'home#help'
  match 'export' => 'home#export'
  match 'visualization' => 'visualization#index'
  match 'dataentry' => 'dashboard#dataentry'
	match 'edit_user_path' => 'users_registrations#edit'
	match 'home' => 'home#index'

	
end

app/controllers/competition_interactions_controller.rb
class CompetitionInteractionsController < ApplicationController
  # GET /competition_interactions
  # GET /competition_interactions.json
  def index
    @competition_interactions = CompetitionInteraction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @competition_interactions }
    end
  end

  # GET /competition_interactions/1
  # GET /competition_interactions/1.json
  def show
    @competition_interaction = CompetitionInteraction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @competition_interaction }
    end
  end

  # GET /competition_interactions/new
  # GET /competition_interactions/new.json
  def new
    @competition_interaction = CompetitionInteraction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @competition_interaction }
    end
  end

  # GET /competition_interactions/1/edit
  def edit
    @competition_interaction = CompetitionInteraction.find(params[:id])
  end

  # POST /competition_interactions
  # POST /competition_interactions.json
  def create
    @competition_interaction = CompetitionInteraction.new(params[:competition_interaction])

    respond_to do |format|
      if @competition_interaction.save
        format.html { redirect_to @competition_interaction, notice: 'Competition interaction was successfully created.' }
        format.json { render json: @competition_interaction, status: :created, location: @competition_interaction }
      else
        format.html { render action: "new" }
        format.json { render json: @competition_interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /competition_interactions/1
  # PUT /competition_interactions/1.json
  def update
    @competition_interaction = CompetitionInteraction.find(params[:id])

    respond_to do |format|
      if @competition_interaction.update_attributes(params[:competition_interaction])
        format.html { redirect_to @competition_interaction, notice: 'Competition interaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @competition_interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competition_interactions/1
  # DELETE /competition_interactions/1.json
  def destroy
    @competition_interaction = CompetitionInteraction.find(params[:id])
    @competition_interaction.destroy

    respond_to do |format|
      format.html { redirect_to competition_interactions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/competition_interactions_helper.rb
module CompetitionInteractionsHelper
end

app/views/competition_interactions/_form.html.erb
<%= form_for(@competition_interaction) do |f| %>
  <% if @competition_interaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition_interaction.errors.count, "error") %> prohibited this competition_interaction from being saved:</h2>

      <ul>
      <% @competition_interaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competition_interactions/edit.html.erb
<h1>Editing competition_interaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @competition_interaction %> |
<%= link_to 'Back', competition_interactions_path %>

app/views/competition_interactions/index.html.erb
<h1>Listing competition_interactions</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @competition_interactions.each do |competition_interaction| %>
  <tr>
    <td><%= link_to 'Show', competition_interaction %></td>
    <td><%= link_to 'Edit', edit_competition_interaction_path(competition_interaction) %></td>
    <td><%= link_to 'Destroy', competition_interaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Competition interaction', new_competition_interaction_path %>

app/views/competition_interactions/new.html.erb
<h1>New competition_interaction</h1>

<%= render 'form' %>

<%= link_to 'Back', competition_interactions_path %>

app/views/competition_interactions/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_competition_interaction_path(@competition_interaction) %> |
<%= link_to 'Back', competition_interactions_path %>